export const UPDATE_PODCASTS = "UPDATE_PODCASTS";
export const ADD_TO_MYPODCASTS = "ADD_TO_MYPODCASTS";
export const REMOVE_FROM_MYPODCASTS = "REMOVE_FROM_MYPODCASTS";

export const UPDATE_GENRES = "UPDATE_GENRES";
export const UPDATE_CURRENT_GENRE = "UPDATE_CURRENT_GENRE";